// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FuturesQuoteSimpleData.proto

package com.waben.stock.futuresgateway.yisheng.common.protobuf;

public final class FuturesQuoteSimpleData {
  private FuturesQuoteSimpleData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FuturesQuoteSimpleDataBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FuturesQuoteSimpleDataBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string time = 1;</code>
     */
    java.lang.String getTime();
    /**
     * <code>optional string time = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>optional string commodityNo = 2;</code>
     */
    java.lang.String getCommodityNo();
    /**
     * <code>optional string commodityNo = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommodityNoBytes();

    /**
     * <code>optional string contractNo = 3;</code>
     */
    java.lang.String getContractNo();
    /**
     * <code>optional string contractNo = 3;</code>
     */
    com.google.protobuf.ByteString
        getContractNoBytes();

    /**
     * <code>optional string lastPrice = 4;</code>
     */
    java.lang.String getLastPrice();
    /**
     * <code>optional string lastPrice = 4;</code>
     */
    com.google.protobuf.ByteString
        getLastPriceBytes();

    /**
     * <code>optional string openPrice = 5;</code>
     */
    java.lang.String getOpenPrice();
    /**
     * <code>optional string openPrice = 5;</code>
     */
    com.google.protobuf.ByteString
        getOpenPriceBytes();

    /**
     * <code>optional string highPrice = 6;</code>
     */
    java.lang.String getHighPrice();
    /**
     * <code>optional string highPrice = 6;</code>
     */
    com.google.protobuf.ByteString
        getHighPriceBytes();

    /**
     * <code>optional string lowPrice = 7;</code>
     */
    java.lang.String getLowPrice();
    /**
     * <code>optional string lowPrice = 7;</code>
     */
    com.google.protobuf.ByteString
        getLowPriceBytes();

    /**
     * <code>optional string closePrice = 8;</code>
     */
    java.lang.String getClosePrice();
    /**
     * <code>optional string closePrice = 8;</code>
     */
    com.google.protobuf.ByteString
        getClosePriceBytes();

    /**
     * <code>optional string bidPrice = 9;</code>
     */
    java.lang.String getBidPrice();
    /**
     * <code>optional string bidPrice = 9;</code>
     */
    com.google.protobuf.ByteString
        getBidPriceBytes();

    /**
     * <code>optional int64 bidSize = 10;</code>
     */
    long getBidSize();

    /**
     * <code>optional string askPrice = 11;</code>
     */
    java.lang.String getAskPrice();
    /**
     * <code>optional string askPrice = 11;</code>
     */
    com.google.protobuf.ByteString
        getAskPriceBytes();

    /**
     * <code>optional int64 askSize = 12;</code>
     */
    long getAskSize();

    /**
     * <code>optional string nowClosePrice = 13;</code>
     */
    java.lang.String getNowClosePrice();
    /**
     * <code>optional string nowClosePrice = 13;</code>
     */
    com.google.protobuf.ByteString
        getNowClosePriceBytes();

    /**
     * <code>optional string preSettlePrice = 14;</code>
     */
    java.lang.String getPreSettlePrice();
    /**
     * <code>optional string preSettlePrice = 14;</code>
     */
    com.google.protobuf.ByteString
        getPreSettlePriceBytes();

    /**
     * <code>optional int64 totalQty = 15;</code>
     */
    long getTotalQty();

    /**
     * <code>optional int64 positionQty = 16;</code>
     */
    long getPositionQty();

    /**
     * <code>optional int64 prePositionQty = 17;</code>
     */
    long getPrePositionQty();
  }
  /**
   * Protobuf type {@code FuturesQuoteSimpleDataBase}
   */
  public  static final class FuturesQuoteSimpleDataBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FuturesQuoteSimpleDataBase)
      FuturesQuoteSimpleDataBaseOrBuilder {
    // Use FuturesQuoteSimpleDataBase.newBuilder() to construct.
    private FuturesQuoteSimpleDataBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FuturesQuoteSimpleDataBase() {
      time_ = "";
      commodityNo_ = "";
      contractNo_ = "";
      lastPrice_ = "";
      openPrice_ = "";
      highPrice_ = "";
      lowPrice_ = "";
      closePrice_ = "";
      bidPrice_ = "";
      bidSize_ = 0L;
      askPrice_ = "";
      askSize_ = 0L;
      nowClosePrice_ = "";
      preSettlePrice_ = "";
      totalQty_ = 0L;
      positionQty_ = 0L;
      prePositionQty_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FuturesQuoteSimpleDataBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              commodityNo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              contractNo_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              lastPrice_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              openPrice_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              highPrice_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              lowPrice_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              closePrice_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              bidPrice_ = s;
              break;
            }
            case 80: {

              bidSize_ = input.readInt64();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              askPrice_ = s;
              break;
            }
            case 96: {

              askSize_ = input.readInt64();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              nowClosePrice_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              preSettlePrice_ = s;
              break;
            }
            case 120: {

              totalQty_ = input.readInt64();
              break;
            }
            case 128: {

              positionQty_ = input.readInt64();
              break;
            }
            case 136: {

              prePositionQty_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.internal_static_FuturesQuoteSimpleDataBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.internal_static_FuturesQuoteSimpleDataBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.class, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object time_;
    /**
     * <code>optional string time = 1;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>optional string time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMODITYNO_FIELD_NUMBER = 2;
    private volatile java.lang.Object commodityNo_;
    /**
     * <code>optional string commodityNo = 2;</code>
     */
    public java.lang.String getCommodityNo() {
      java.lang.Object ref = commodityNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commodityNo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string commodityNo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommodityNoBytes() {
      java.lang.Object ref = commodityNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commodityNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTNO_FIELD_NUMBER = 3;
    private volatile java.lang.Object contractNo_;
    /**
     * <code>optional string contractNo = 3;</code>
     */
    public java.lang.String getContractNo() {
      java.lang.Object ref = contractNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractNo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contractNo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContractNoBytes() {
      java.lang.Object ref = contractNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTPRICE_FIELD_NUMBER = 4;
    private volatile java.lang.Object lastPrice_;
    /**
     * <code>optional string lastPrice = 4;</code>
     */
    public java.lang.String getLastPrice() {
      java.lang.Object ref = lastPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastPrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string lastPrice = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLastPriceBytes() {
      java.lang.Object ref = lastPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPENPRICE_FIELD_NUMBER = 5;
    private volatile java.lang.Object openPrice_;
    /**
     * <code>optional string openPrice = 5;</code>
     */
    public java.lang.String getOpenPrice() {
      java.lang.Object ref = openPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        openPrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string openPrice = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOpenPriceBytes() {
      java.lang.Object ref = openPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HIGHPRICE_FIELD_NUMBER = 6;
    private volatile java.lang.Object highPrice_;
    /**
     * <code>optional string highPrice = 6;</code>
     */
    public java.lang.String getHighPrice() {
      java.lang.Object ref = highPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        highPrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string highPrice = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHighPriceBytes() {
      java.lang.Object ref = highPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        highPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOWPRICE_FIELD_NUMBER = 7;
    private volatile java.lang.Object lowPrice_;
    /**
     * <code>optional string lowPrice = 7;</code>
     */
    public java.lang.String getLowPrice() {
      java.lang.Object ref = lowPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lowPrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string lowPrice = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLowPriceBytes() {
      java.lang.Object ref = lowPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lowPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOSEPRICE_FIELD_NUMBER = 8;
    private volatile java.lang.Object closePrice_;
    /**
     * <code>optional string closePrice = 8;</code>
     */
    public java.lang.String getClosePrice() {
      java.lang.Object ref = closePrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        closePrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string closePrice = 8;</code>
     */
    public com.google.protobuf.ByteString
        getClosePriceBytes() {
      java.lang.Object ref = closePrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        closePrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDPRICE_FIELD_NUMBER = 9;
    private volatile java.lang.Object bidPrice_;
    /**
     * <code>optional string bidPrice = 9;</code>
     */
    public java.lang.String getBidPrice() {
      java.lang.Object ref = bidPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bidPrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string bidPrice = 9;</code>
     */
    public com.google.protobuf.ByteString
        getBidPriceBytes() {
      java.lang.Object ref = bidPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDSIZE_FIELD_NUMBER = 10;
    private long bidSize_;
    /**
     * <code>optional int64 bidSize = 10;</code>
     */
    public long getBidSize() {
      return bidSize_;
    }

    public static final int ASKPRICE_FIELD_NUMBER = 11;
    private volatile java.lang.Object askPrice_;
    /**
     * <code>optional string askPrice = 11;</code>
     */
    public java.lang.String getAskPrice() {
      java.lang.Object ref = askPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        askPrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string askPrice = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAskPriceBytes() {
      java.lang.Object ref = askPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        askPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASKSIZE_FIELD_NUMBER = 12;
    private long askSize_;
    /**
     * <code>optional int64 askSize = 12;</code>
     */
    public long getAskSize() {
      return askSize_;
    }

    public static final int NOWCLOSEPRICE_FIELD_NUMBER = 13;
    private volatile java.lang.Object nowClosePrice_;
    /**
     * <code>optional string nowClosePrice = 13;</code>
     */
    public java.lang.String getNowClosePrice() {
      java.lang.Object ref = nowClosePrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nowClosePrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string nowClosePrice = 13;</code>
     */
    public com.google.protobuf.ByteString
        getNowClosePriceBytes() {
      java.lang.Object ref = nowClosePrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nowClosePrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRESETTLEPRICE_FIELD_NUMBER = 14;
    private volatile java.lang.Object preSettlePrice_;
    /**
     * <code>optional string preSettlePrice = 14;</code>
     */
    public java.lang.String getPreSettlePrice() {
      java.lang.Object ref = preSettlePrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preSettlePrice_ = s;
        return s;
      }
    }
    /**
     * <code>optional string preSettlePrice = 14;</code>
     */
    public com.google.protobuf.ByteString
        getPreSettlePriceBytes() {
      java.lang.Object ref = preSettlePrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preSettlePrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALQTY_FIELD_NUMBER = 15;
    private long totalQty_;
    /**
     * <code>optional int64 totalQty = 15;</code>
     */
    public long getTotalQty() {
      return totalQty_;
    }

    public static final int POSITIONQTY_FIELD_NUMBER = 16;
    private long positionQty_;
    /**
     * <code>optional int64 positionQty = 16;</code>
     */
    public long getPositionQty() {
      return positionQty_;
    }

    public static final int PREPOSITIONQTY_FIELD_NUMBER = 17;
    private long prePositionQty_;
    /**
     * <code>optional int64 prePositionQty = 17;</code>
     */
    public long getPrePositionQty() {
      return prePositionQty_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, time_);
      }
      if (!getCommodityNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commodityNo_);
      }
      if (!getContractNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contractNo_);
      }
      if (!getLastPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastPrice_);
      }
      if (!getOpenPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, openPrice_);
      }
      if (!getHighPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, highPrice_);
      }
      if (!getLowPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, lowPrice_);
      }
      if (!getClosePriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, closePrice_);
      }
      if (!getBidPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, bidPrice_);
      }
      if (bidSize_ != 0L) {
        output.writeInt64(10, bidSize_);
      }
      if (!getAskPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, askPrice_);
      }
      if (askSize_ != 0L) {
        output.writeInt64(12, askSize_);
      }
      if (!getNowClosePriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, nowClosePrice_);
      }
      if (!getPreSettlePriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, preSettlePrice_);
      }
      if (totalQty_ != 0L) {
        output.writeInt64(15, totalQty_);
      }
      if (positionQty_ != 0L) {
        output.writeInt64(16, positionQty_);
      }
      if (prePositionQty_ != 0L) {
        output.writeInt64(17, prePositionQty_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, time_);
      }
      if (!getCommodityNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commodityNo_);
      }
      if (!getContractNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contractNo_);
      }
      if (!getLastPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastPrice_);
      }
      if (!getOpenPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, openPrice_);
      }
      if (!getHighPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, highPrice_);
      }
      if (!getLowPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, lowPrice_);
      }
      if (!getClosePriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, closePrice_);
      }
      if (!getBidPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, bidPrice_);
      }
      if (bidSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, bidSize_);
      }
      if (!getAskPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, askPrice_);
      }
      if (askSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, askSize_);
      }
      if (!getNowClosePriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, nowClosePrice_);
      }
      if (!getPreSettlePriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, preSettlePrice_);
      }
      if (totalQty_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, totalQty_);
      }
      if (positionQty_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(16, positionQty_);
      }
      if (prePositionQty_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, prePositionQty_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase)) {
        return super.equals(obj);
      }
      com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase other = (com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase) obj;

      boolean result = true;
      result = result && getTime()
          .equals(other.getTime());
      result = result && getCommodityNo()
          .equals(other.getCommodityNo());
      result = result && getContractNo()
          .equals(other.getContractNo());
      result = result && getLastPrice()
          .equals(other.getLastPrice());
      result = result && getOpenPrice()
          .equals(other.getOpenPrice());
      result = result && getHighPrice()
          .equals(other.getHighPrice());
      result = result && getLowPrice()
          .equals(other.getLowPrice());
      result = result && getClosePrice()
          .equals(other.getClosePrice());
      result = result && getBidPrice()
          .equals(other.getBidPrice());
      result = result && (getBidSize()
          == other.getBidSize());
      result = result && getAskPrice()
          .equals(other.getAskPrice());
      result = result && (getAskSize()
          == other.getAskSize());
      result = result && getNowClosePrice()
          .equals(other.getNowClosePrice());
      result = result && getPreSettlePrice()
          .equals(other.getPreSettlePrice());
      result = result && (getTotalQty()
          == other.getTotalQty());
      result = result && (getPositionQty()
          == other.getPositionQty());
      result = result && (getPrePositionQty()
          == other.getPrePositionQty());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + COMMODITYNO_FIELD_NUMBER;
      hash = (53 * hash) + getCommodityNo().hashCode();
      hash = (37 * hash) + CONTRACTNO_FIELD_NUMBER;
      hash = (53 * hash) + getContractNo().hashCode();
      hash = (37 * hash) + LASTPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getLastPrice().hashCode();
      hash = (37 * hash) + OPENPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getOpenPrice().hashCode();
      hash = (37 * hash) + HIGHPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getHighPrice().hashCode();
      hash = (37 * hash) + LOWPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getLowPrice().hashCode();
      hash = (37 * hash) + CLOSEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getClosePrice().hashCode();
      hash = (37 * hash) + BIDPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getBidPrice().hashCode();
      hash = (37 * hash) + BIDSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBidSize());
      hash = (37 * hash) + ASKPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getAskPrice().hashCode();
      hash = (37 * hash) + ASKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAskSize());
      hash = (37 * hash) + NOWCLOSEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getNowClosePrice().hashCode();
      hash = (37 * hash) + PRESETTLEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPreSettlePrice().hashCode();
      hash = (37 * hash) + TOTALQTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalQty());
      hash = (37 * hash) + POSITIONQTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPositionQty());
      hash = (37 * hash) + PREPOSITIONQTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrePositionQty());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FuturesQuoteSimpleDataBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FuturesQuoteSimpleDataBase)
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.internal_static_FuturesQuoteSimpleDataBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.internal_static_FuturesQuoteSimpleDataBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.class, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder.class);
      }

      // Construct using com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = "";

        commodityNo_ = "";

        contractNo_ = "";

        lastPrice_ = "";

        openPrice_ = "";

        highPrice_ = "";

        lowPrice_ = "";

        closePrice_ = "";

        bidPrice_ = "";

        bidSize_ = 0L;

        askPrice_ = "";

        askSize_ = 0L;

        nowClosePrice_ = "";

        preSettlePrice_ = "";

        totalQty_ = 0L;

        positionQty_ = 0L;

        prePositionQty_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.internal_static_FuturesQuoteSimpleDataBase_descriptor;
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase getDefaultInstanceForType() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.getDefaultInstance();
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase build() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase buildPartial() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase result = new com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase(this);
        result.time_ = time_;
        result.commodityNo_ = commodityNo_;
        result.contractNo_ = contractNo_;
        result.lastPrice_ = lastPrice_;
        result.openPrice_ = openPrice_;
        result.highPrice_ = highPrice_;
        result.lowPrice_ = lowPrice_;
        result.closePrice_ = closePrice_;
        result.bidPrice_ = bidPrice_;
        result.bidSize_ = bidSize_;
        result.askPrice_ = askPrice_;
        result.askSize_ = askSize_;
        result.nowClosePrice_ = nowClosePrice_;
        result.preSettlePrice_ = preSettlePrice_;
        result.totalQty_ = totalQty_;
        result.positionQty_ = positionQty_;
        result.prePositionQty_ = prePositionQty_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase) {
          return mergeFrom((com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase other) {
        if (other == com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.getDefaultInstance()) return this;
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (!other.getCommodityNo().isEmpty()) {
          commodityNo_ = other.commodityNo_;
          onChanged();
        }
        if (!other.getContractNo().isEmpty()) {
          contractNo_ = other.contractNo_;
          onChanged();
        }
        if (!other.getLastPrice().isEmpty()) {
          lastPrice_ = other.lastPrice_;
          onChanged();
        }
        if (!other.getOpenPrice().isEmpty()) {
          openPrice_ = other.openPrice_;
          onChanged();
        }
        if (!other.getHighPrice().isEmpty()) {
          highPrice_ = other.highPrice_;
          onChanged();
        }
        if (!other.getLowPrice().isEmpty()) {
          lowPrice_ = other.lowPrice_;
          onChanged();
        }
        if (!other.getClosePrice().isEmpty()) {
          closePrice_ = other.closePrice_;
          onChanged();
        }
        if (!other.getBidPrice().isEmpty()) {
          bidPrice_ = other.bidPrice_;
          onChanged();
        }
        if (other.getBidSize() != 0L) {
          setBidSize(other.getBidSize());
        }
        if (!other.getAskPrice().isEmpty()) {
          askPrice_ = other.askPrice_;
          onChanged();
        }
        if (other.getAskSize() != 0L) {
          setAskSize(other.getAskSize());
        }
        if (!other.getNowClosePrice().isEmpty()) {
          nowClosePrice_ = other.nowClosePrice_;
          onChanged();
        }
        if (!other.getPreSettlePrice().isEmpty()) {
          preSettlePrice_ = other.preSettlePrice_;
          onChanged();
        }
        if (other.getTotalQty() != 0L) {
          setTotalQty(other.getTotalQty());
        }
        if (other.getPositionQty() != 0L) {
          setPositionQty(other.getPositionQty());
        }
        if (other.getPrePositionQty() != 0L) {
          setPrePositionQty(other.getPrePositionQty());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>optional string time = 1;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string time = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string time = 1;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 1;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commodityNo_ = "";
      /**
       * <code>optional string commodityNo = 2;</code>
       */
      public java.lang.String getCommodityNo() {
        java.lang.Object ref = commodityNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commodityNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commodityNo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommodityNoBytes() {
        java.lang.Object ref = commodityNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commodityNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commodityNo = 2;</code>
       */
      public Builder setCommodityNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commodityNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commodityNo = 2;</code>
       */
      public Builder clearCommodityNo() {
        
        commodityNo_ = getDefaultInstance().getCommodityNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commodityNo = 2;</code>
       */
      public Builder setCommodityNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commodityNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contractNo_ = "";
      /**
       * <code>optional string contractNo = 3;</code>
       */
      public java.lang.String getContractNo() {
        java.lang.Object ref = contractNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contractNo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContractNoBytes() {
        java.lang.Object ref = contractNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contractNo = 3;</code>
       */
      public Builder setContractNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contractNo = 3;</code>
       */
      public Builder clearContractNo() {
        
        contractNo_ = getDefaultInstance().getContractNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contractNo = 3;</code>
       */
      public Builder setContractNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contractNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastPrice_ = "";
      /**
       * <code>optional string lastPrice = 4;</code>
       */
      public java.lang.String getLastPrice() {
        java.lang.Object ref = lastPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastPrice = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLastPriceBytes() {
        java.lang.Object ref = lastPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastPrice = 4;</code>
       */
      public Builder setLastPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastPrice = 4;</code>
       */
      public Builder clearLastPrice() {
        
        lastPrice_ = getDefaultInstance().getLastPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastPrice = 4;</code>
       */
      public Builder setLastPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object openPrice_ = "";
      /**
       * <code>optional string openPrice = 5;</code>
       */
      public java.lang.String getOpenPrice() {
        java.lang.Object ref = openPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          openPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string openPrice = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOpenPriceBytes() {
        java.lang.Object ref = openPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          openPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string openPrice = 5;</code>
       */
      public Builder setOpenPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        openPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string openPrice = 5;</code>
       */
      public Builder clearOpenPrice() {
        
        openPrice_ = getDefaultInstance().getOpenPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string openPrice = 5;</code>
       */
      public Builder setOpenPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        openPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object highPrice_ = "";
      /**
       * <code>optional string highPrice = 6;</code>
       */
      public java.lang.String getHighPrice() {
        java.lang.Object ref = highPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          highPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string highPrice = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHighPriceBytes() {
        java.lang.Object ref = highPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          highPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string highPrice = 6;</code>
       */
      public Builder setHighPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        highPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string highPrice = 6;</code>
       */
      public Builder clearHighPrice() {
        
        highPrice_ = getDefaultInstance().getHighPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string highPrice = 6;</code>
       */
      public Builder setHighPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        highPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lowPrice_ = "";
      /**
       * <code>optional string lowPrice = 7;</code>
       */
      public java.lang.String getLowPrice() {
        java.lang.Object ref = lowPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lowPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lowPrice = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLowPriceBytes() {
        java.lang.Object ref = lowPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lowPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lowPrice = 7;</code>
       */
      public Builder setLowPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lowPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lowPrice = 7;</code>
       */
      public Builder clearLowPrice() {
        
        lowPrice_ = getDefaultInstance().getLowPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lowPrice = 7;</code>
       */
      public Builder setLowPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lowPrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object closePrice_ = "";
      /**
       * <code>optional string closePrice = 8;</code>
       */
      public java.lang.String getClosePrice() {
        java.lang.Object ref = closePrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          closePrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string closePrice = 8;</code>
       */
      public com.google.protobuf.ByteString
          getClosePriceBytes() {
        java.lang.Object ref = closePrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          closePrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string closePrice = 8;</code>
       */
      public Builder setClosePrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        closePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string closePrice = 8;</code>
       */
      public Builder clearClosePrice() {
        
        closePrice_ = getDefaultInstance().getClosePrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string closePrice = 8;</code>
       */
      public Builder setClosePriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        closePrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bidPrice_ = "";
      /**
       * <code>optional string bidPrice = 9;</code>
       */
      public java.lang.String getBidPrice() {
        java.lang.Object ref = bidPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bidPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bidPrice = 9;</code>
       */
      public com.google.protobuf.ByteString
          getBidPriceBytes() {
        java.lang.Object ref = bidPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bidPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bidPrice = 9;</code>
       */
      public Builder setBidPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bidPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidPrice = 9;</code>
       */
      public Builder clearBidPrice() {
        
        bidPrice_ = getDefaultInstance().getBidPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidPrice = 9;</code>
       */
      public Builder setBidPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bidPrice_ = value;
        onChanged();
        return this;
      }

      private long bidSize_ ;
      /**
       * <code>optional int64 bidSize = 10;</code>
       */
      public long getBidSize() {
        return bidSize_;
      }
      /**
       * <code>optional int64 bidSize = 10;</code>
       */
      public Builder setBidSize(long value) {
        
        bidSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 bidSize = 10;</code>
       */
      public Builder clearBidSize() {
        
        bidSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object askPrice_ = "";
      /**
       * <code>optional string askPrice = 11;</code>
       */
      public java.lang.String getAskPrice() {
        java.lang.Object ref = askPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          askPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string askPrice = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAskPriceBytes() {
        java.lang.Object ref = askPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          askPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string askPrice = 11;</code>
       */
      public Builder setAskPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        askPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string askPrice = 11;</code>
       */
      public Builder clearAskPrice() {
        
        askPrice_ = getDefaultInstance().getAskPrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string askPrice = 11;</code>
       */
      public Builder setAskPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        askPrice_ = value;
        onChanged();
        return this;
      }

      private long askSize_ ;
      /**
       * <code>optional int64 askSize = 12;</code>
       */
      public long getAskSize() {
        return askSize_;
      }
      /**
       * <code>optional int64 askSize = 12;</code>
       */
      public Builder setAskSize(long value) {
        
        askSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 askSize = 12;</code>
       */
      public Builder clearAskSize() {
        
        askSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object nowClosePrice_ = "";
      /**
       * <code>optional string nowClosePrice = 13;</code>
       */
      public java.lang.String getNowClosePrice() {
        java.lang.Object ref = nowClosePrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nowClosePrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nowClosePrice = 13;</code>
       */
      public com.google.protobuf.ByteString
          getNowClosePriceBytes() {
        java.lang.Object ref = nowClosePrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nowClosePrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nowClosePrice = 13;</code>
       */
      public Builder setNowClosePrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nowClosePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nowClosePrice = 13;</code>
       */
      public Builder clearNowClosePrice() {
        
        nowClosePrice_ = getDefaultInstance().getNowClosePrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nowClosePrice = 13;</code>
       */
      public Builder setNowClosePriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nowClosePrice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object preSettlePrice_ = "";
      /**
       * <code>optional string preSettlePrice = 14;</code>
       */
      public java.lang.String getPreSettlePrice() {
        java.lang.Object ref = preSettlePrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          preSettlePrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string preSettlePrice = 14;</code>
       */
      public com.google.protobuf.ByteString
          getPreSettlePriceBytes() {
        java.lang.Object ref = preSettlePrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          preSettlePrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string preSettlePrice = 14;</code>
       */
      public Builder setPreSettlePrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        preSettlePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string preSettlePrice = 14;</code>
       */
      public Builder clearPreSettlePrice() {
        
        preSettlePrice_ = getDefaultInstance().getPreSettlePrice();
        onChanged();
        return this;
      }
      /**
       * <code>optional string preSettlePrice = 14;</code>
       */
      public Builder setPreSettlePriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        preSettlePrice_ = value;
        onChanged();
        return this;
      }

      private long totalQty_ ;
      /**
       * <code>optional int64 totalQty = 15;</code>
       */
      public long getTotalQty() {
        return totalQty_;
      }
      /**
       * <code>optional int64 totalQty = 15;</code>
       */
      public Builder setTotalQty(long value) {
        
        totalQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 totalQty = 15;</code>
       */
      public Builder clearTotalQty() {
        
        totalQty_ = 0L;
        onChanged();
        return this;
      }

      private long positionQty_ ;
      /**
       * <code>optional int64 positionQty = 16;</code>
       */
      public long getPositionQty() {
        return positionQty_;
      }
      /**
       * <code>optional int64 positionQty = 16;</code>
       */
      public Builder setPositionQty(long value) {
        
        positionQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 positionQty = 16;</code>
       */
      public Builder clearPositionQty() {
        
        positionQty_ = 0L;
        onChanged();
        return this;
      }

      private long prePositionQty_ ;
      /**
       * <code>optional int64 prePositionQty = 17;</code>
       */
      public long getPrePositionQty() {
        return prePositionQty_;
      }
      /**
       * <code>optional int64 prePositionQty = 17;</code>
       */
      public Builder setPrePositionQty(long value) {
        
        prePositionQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 prePositionQty = 17;</code>
       */
      public Builder clearPrePositionQty() {
        
        prePositionQty_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FuturesQuoteSimpleDataBase)
    }

    // @@protoc_insertion_point(class_scope:FuturesQuoteSimpleDataBase)
    private static final com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase();
    }

    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FuturesQuoteSimpleDataBase>
        PARSER = new com.google.protobuf.AbstractParser<FuturesQuoteSimpleDataBase>() {
      public FuturesQuoteSimpleDataBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FuturesQuoteSimpleDataBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FuturesQuoteSimpleDataBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FuturesQuoteSimpleDataBase> getParserForType() {
      return PARSER;
    }

    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FuturesQuoteSimpleDataBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FuturesQuoteSimpleDataBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034FuturesQuoteSimpleData.proto\"\346\002\n\032Futur" +
      "esQuoteSimpleDataBase\022\014\n\004time\030\001 \001(\t\022\023\n\013c" +
      "ommodityNo\030\002 \001(\t\022\022\n\ncontractNo\030\003 \001(\t\022\021\n\t" +
      "lastPrice\030\004 \001(\t\022\021\n\topenPrice\030\005 \001(\t\022\021\n\thi" +
      "ghPrice\030\006 \001(\t\022\020\n\010lowPrice\030\007 \001(\t\022\022\n\nclose" +
      "Price\030\010 \001(\t\022\020\n\010bidPrice\030\t \001(\t\022\017\n\007bidSize" +
      "\030\n \001(\003\022\020\n\010askPrice\030\013 \001(\t\022\017\n\007askSize\030\014 \001(" +
      "\003\022\025\n\rnowClosePrice\030\r \001(\t\022\026\n\016preSettlePri" +
      "ce\030\016 \001(\t\022\020\n\010totalQty\030\017 \001(\003\022\023\n\013positionQt" +
      "y\030\020 \001(\003\022\026\n\016prePositionQty\030\021 \001(\003BP\n6com.w",
      "aben.stock.futuresgateway.yisheng.common" +
      ".protobufB\026FuturesQuoteSimpleDatab\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FuturesQuoteSimpleDataBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FuturesQuoteSimpleDataBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FuturesQuoteSimpleDataBase_descriptor,
        new java.lang.String[] { "Time", "CommodityNo", "ContractNo", "LastPrice", "OpenPrice", "HighPrice", "LowPrice", "ClosePrice", "BidPrice", "BidSize", "AskPrice", "AskSize", "NowClosePrice", "PreSettlePrice", "TotalQty", "PositionQty", "PrePositionQty", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
