// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.waben.stock.futuresgateway.yisheng.common.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string clientId = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>optional string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>optional .CommandType cmd = 2;</code>
     */
    int getCmdValue();
    /**
     * <code>optional .CommandType cmd = 2;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType getCmd();

    /**
     * <code>optional int64 type = 3;</code>
     */
    long getType();

    /**
     * <code>optional int64 requestType = 4;</code>
     */
    long getRequestType();

    /**
     * <code>optional string data = 5;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>optional .FuturesQuoteDataBase fq = 6;</code>
     */
    boolean hasFq();
    /**
     * <code>optional .FuturesQuoteDataBase fq = 6;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase getFq();
    /**
     * <code>optional .FuturesQuoteDataBase fq = 6;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder getFqOrBuilder();

    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    java.util.List<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase> 
        getFqListList();
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase getFqList(int index);
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    int getFqListCount();
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    java.util.List<? extends com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder> 
        getFqListOrBuilderList();
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder getFqListOrBuilder(
        int index);

    /**
     * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
     */
    boolean hasFullFq();
    /**
     * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase getFullFq();
    /**
     * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
     */
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBaseOrBuilder getFullFqOrBuilder();
  }
  /**
   * Protobuf type {@code MessageBase}
   */
  public  static final class MessageBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageBase)
      MessageBaseOrBuilder {
    // Use MessageBase.newBuilder() to construct.
    private MessageBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageBase() {
      clientId_ = "";
      cmd_ = 0;
      type_ = 0L;
      requestType_ = 0L;
      data_ = "";
      fqList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 24: {

              type_ = input.readInt64();
              break;
            }
            case 32: {

              requestType_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 50: {
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder subBuilder = null;
              if (fq_ != null) {
                subBuilder = fq_.toBuilder();
              }
              fq_ = input.readMessage(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fq_);
                fq_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                fqList_ = new java.util.ArrayList<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase>();
                mutable_bitField0_ |= 0x00000040;
              }
              fqList_.add(
                  input.readMessage(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.parser(), extensionRegistry));
              break;
            }
            case 66: {
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.Builder subBuilder = null;
              if (fullFq_ != null) {
                subBuilder = fullFq_.toBuilder();
              }
              fullFq_ = input.readMessage(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fullFq_);
                fullFq_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          fqList_ = java.util.Collections.unmodifiableList(fqList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.internal_static_MessageBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.internal_static_MessageBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.class, com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>optional string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>optional .CommandType cmd = 2;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>optional .CommandType cmd = 2;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType getCmd() {
      com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType result = com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.valueOf(cmd_);
      return result == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.UNRECOGNIZED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private long type_;
    /**
     * <code>optional int64 type = 3;</code>
     */
    public long getType() {
      return type_;
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 4;
    private long requestType_;
    /**
     * <code>optional int64 requestType = 4;</code>
     */
    public long getRequestType() {
      return requestType_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>optional string data = 5;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>optional string data = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FQ_FIELD_NUMBER = 6;
    private com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase fq_;
    /**
     * <code>optional .FuturesQuoteDataBase fq = 6;</code>
     */
    public boolean hasFq() {
      return fq_ != null;
    }
    /**
     * <code>optional .FuturesQuoteDataBase fq = 6;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase getFq() {
      return fq_ == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.getDefaultInstance() : fq_;
    }
    /**
     * <code>optional .FuturesQuoteDataBase fq = 6;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder getFqOrBuilder() {
      return getFq();
    }

    public static final int FQLIST_FIELD_NUMBER = 7;
    private java.util.List<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase> fqList_;
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    public java.util.List<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase> getFqListList() {
      return fqList_;
    }
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    public java.util.List<? extends com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder> 
        getFqListOrBuilderList() {
      return fqList_;
    }
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    public int getFqListCount() {
      return fqList_.size();
    }
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase getFqList(int index) {
      return fqList_.get(index);
    }
    /**
     * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder getFqListOrBuilder(
        int index) {
      return fqList_.get(index);
    }

    public static final int FULLFQ_FIELD_NUMBER = 8;
    private com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase fullFq_;
    /**
     * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
     */
    public boolean hasFullFq() {
      return fullFq_ != null;
    }
    /**
     * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase getFullFq() {
      return fullFq_ == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.getDefaultInstance() : fullFq_;
    }
    /**
     * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
     */
    public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBaseOrBuilder getFullFqOrBuilder() {
      return getFullFq();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (cmd_ != com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.NONE.getNumber()) {
        output.writeEnum(2, cmd_);
      }
      if (type_ != 0L) {
        output.writeInt64(3, type_);
      }
      if (requestType_ != 0L) {
        output.writeInt64(4, requestType_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      if (fq_ != null) {
        output.writeMessage(6, getFq());
      }
      for (int i = 0; i < fqList_.size(); i++) {
        output.writeMessage(7, fqList_.get(i));
      }
      if (fullFq_ != null) {
        output.writeMessage(8, getFullFq());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (cmd_ != com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cmd_);
      }
      if (type_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, type_);
      }
      if (requestType_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, requestType_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      if (fq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getFq());
      }
      for (int i = 0; i < fqList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, fqList_.get(i));
      }
      if (fullFq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getFullFq());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase)) {
        return super.equals(obj);
      }
      com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase other = (com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && cmd_ == other.cmd_;
      result = result && (getType()
          == other.getType());
      result = result && (getRequestType()
          == other.getRequestType());
      result = result && getData()
          .equals(other.getData());
      result = result && (hasFq() == other.hasFq());
      if (hasFq()) {
        result = result && getFq()
            .equals(other.getFq());
      }
      result = result && getFqListList()
          .equals(other.getFqListList());
      result = result && (hasFullFq() == other.hasFullFq());
      if (hasFullFq()) {
        result = result && getFullFq()
            .equals(other.getFullFq());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getType());
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestType());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      if (hasFq()) {
        hash = (37 * hash) + FQ_FIELD_NUMBER;
        hash = (53 * hash) + getFq().hashCode();
      }
      if (getFqListCount() > 0) {
        hash = (37 * hash) + FQLIST_FIELD_NUMBER;
        hash = (53 * hash) + getFqListList().hashCode();
      }
      if (hasFullFq()) {
        hash = (37 * hash) + FULLFQ_FIELD_NUMBER;
        hash = (53 * hash) + getFullFq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageBase)
        com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.internal_static_MessageBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.internal_static_MessageBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.class, com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.Builder.class);
      }

      // Construct using com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFqListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = "";

        cmd_ = 0;

        type_ = 0L;

        requestType_ = 0L;

        data_ = "";

        if (fqBuilder_ == null) {
          fq_ = null;
        } else {
          fq_ = null;
          fqBuilder_ = null;
        }
        if (fqListBuilder_ == null) {
          fqList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          fqListBuilder_.clear();
        }
        if (fullFqBuilder_ == null) {
          fullFq_ = null;
        } else {
          fullFq_ = null;
          fullFqBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.internal_static_MessageBase_descriptor;
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase getDefaultInstanceForType() {
        return com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.getDefaultInstance();
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase build() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase buildPartial() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase result = new com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.clientId_ = clientId_;
        result.cmd_ = cmd_;
        result.type_ = type_;
        result.requestType_ = requestType_;
        result.data_ = data_;
        if (fqBuilder_ == null) {
          result.fq_ = fq_;
        } else {
          result.fq_ = fqBuilder_.build();
        }
        if (fqListBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            fqList_ = java.util.Collections.unmodifiableList(fqList_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.fqList_ = fqList_;
        } else {
          result.fqList_ = fqListBuilder_.build();
        }
        if (fullFqBuilder_ == null) {
          result.fullFq_ = fullFq_;
        } else {
          result.fullFq_ = fullFqBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase) {
          return mergeFrom((com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase other) {
        if (other == com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.getType() != 0L) {
          setType(other.getType());
        }
        if (other.getRequestType() != 0L) {
          setRequestType(other.getRequestType());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.hasFq()) {
          mergeFq(other.getFq());
        }
        if (fqListBuilder_ == null) {
          if (!other.fqList_.isEmpty()) {
            if (fqList_.isEmpty()) {
              fqList_ = other.fqList_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureFqListIsMutable();
              fqList_.addAll(other.fqList_);
            }
            onChanged();
          }
        } else {
          if (!other.fqList_.isEmpty()) {
            if (fqListBuilder_.isEmpty()) {
              fqListBuilder_.dispose();
              fqListBuilder_ = null;
              fqList_ = other.fqList_;
              bitField0_ = (bitField0_ & ~0x00000040);
              fqListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFqListFieldBuilder() : null;
            } else {
              fqListBuilder_.addAllMessages(other.fqList_);
            }
          }
        }
        if (other.hasFullFq()) {
          mergeFullFq(other.getFullFq());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientId_ = "";
      /**
       * <code>optional string clientId = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>optional .CommandType cmd = 2;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>optional .CommandType cmd = 2;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CommandType cmd = 2;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType getCmd() {
        com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType result = com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.valueOf(cmd_);
        return result == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .CommandType cmd = 2;</code>
       */
      public Builder setCmd(com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .CommandType cmd = 2;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private long type_ ;
      /**
       * <code>optional int64 type = 3;</code>
       */
      public long getType() {
        return type_;
      }
      /**
       * <code>optional int64 type = 3;</code>
       */
      public Builder setType(long value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0L;
        onChanged();
        return this;
      }

      private long requestType_ ;
      /**
       * <code>optional int64 requestType = 4;</code>
       */
      public long getRequestType() {
        return requestType_;
      }
      /**
       * <code>optional int64 requestType = 4;</code>
       */
      public Builder setRequestType(long value) {
        
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 requestType = 4;</code>
       */
      public Builder clearRequestType() {
        
        requestType_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 5;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 5;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 5;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase fq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder> fqBuilder_;
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public boolean hasFq() {
        return fqBuilder_ != null || fq_ != null;
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase getFq() {
        if (fqBuilder_ == null) {
          return fq_ == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.getDefaultInstance() : fq_;
        } else {
          return fqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public Builder setFq(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase value) {
        if (fqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fq_ = value;
          onChanged();
        } else {
          fqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public Builder setFq(
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder builderForValue) {
        if (fqBuilder_ == null) {
          fq_ = builderForValue.build();
          onChanged();
        } else {
          fqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public Builder mergeFq(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase value) {
        if (fqBuilder_ == null) {
          if (fq_ != null) {
            fq_ =
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.newBuilder(fq_).mergeFrom(value).buildPartial();
          } else {
            fq_ = value;
          }
          onChanged();
        } else {
          fqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public Builder clearFq() {
        if (fqBuilder_ == null) {
          fq_ = null;
          onChanged();
        } else {
          fq_ = null;
          fqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder getFqBuilder() {
        
        onChanged();
        return getFqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder getFqOrBuilder() {
        if (fqBuilder_ != null) {
          return fqBuilder_.getMessageOrBuilder();
        } else {
          return fq_ == null ?
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.getDefaultInstance() : fq_;
        }
      }
      /**
       * <code>optional .FuturesQuoteDataBase fq = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder> 
          getFqFieldBuilder() {
        if (fqBuilder_ == null) {
          fqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.FuturesQuoteDataBaseOrBuilder>(
                  getFq(),
                  getParentForChildren(),
                  isClean());
          fq_ = null;
        }
        return fqBuilder_;
      }

      private java.util.List<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase> fqList_ =
        java.util.Collections.emptyList();
      private void ensureFqListIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          fqList_ = new java.util.ArrayList<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase>(fqList_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder> fqListBuilder_;

      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public java.util.List<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase> getFqListList() {
        if (fqListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fqList_);
        } else {
          return fqListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public int getFqListCount() {
        if (fqListBuilder_ == null) {
          return fqList_.size();
        } else {
          return fqListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase getFqList(int index) {
        if (fqListBuilder_ == null) {
          return fqList_.get(index);
        } else {
          return fqListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder setFqList(
          int index, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase value) {
        if (fqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFqListIsMutable();
          fqList_.set(index, value);
          onChanged();
        } else {
          fqListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder setFqList(
          int index, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder builderForValue) {
        if (fqListBuilder_ == null) {
          ensureFqListIsMutable();
          fqList_.set(index, builderForValue.build());
          onChanged();
        } else {
          fqListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder addFqList(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase value) {
        if (fqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFqListIsMutable();
          fqList_.add(value);
          onChanged();
        } else {
          fqListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder addFqList(
          int index, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase value) {
        if (fqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFqListIsMutable();
          fqList_.add(index, value);
          onChanged();
        } else {
          fqListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder addFqList(
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder builderForValue) {
        if (fqListBuilder_ == null) {
          ensureFqListIsMutable();
          fqList_.add(builderForValue.build());
          onChanged();
        } else {
          fqListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder addFqList(
          int index, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder builderForValue) {
        if (fqListBuilder_ == null) {
          ensureFqListIsMutable();
          fqList_.add(index, builderForValue.build());
          onChanged();
        } else {
          fqListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder addAllFqList(
          java.lang.Iterable<? extends com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase> values) {
        if (fqListBuilder_ == null) {
          ensureFqListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fqList_);
          onChanged();
        } else {
          fqListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder clearFqList() {
        if (fqListBuilder_ == null) {
          fqList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          fqListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public Builder removeFqList(int index) {
        if (fqListBuilder_ == null) {
          ensureFqListIsMutable();
          fqList_.remove(index);
          onChanged();
        } else {
          fqListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder getFqListBuilder(
          int index) {
        return getFqListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder getFqListOrBuilder(
          int index) {
        if (fqListBuilder_ == null) {
          return fqList_.get(index);  } else {
          return fqListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public java.util.List<? extends com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder> 
           getFqListOrBuilderList() {
        if (fqListBuilder_ != null) {
          return fqListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fqList_);
        }
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder addFqListBuilder() {
        return getFqListFieldBuilder().addBuilder(
            com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.getDefaultInstance());
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder addFqListBuilder(
          int index) {
        return getFqListFieldBuilder().addBuilder(
            index, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.getDefaultInstance());
      }
      /**
       * <code>repeated .FuturesQuoteSimpleDataBase fqList = 7;</code>
       */
      public java.util.List<com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder> 
           getFqListBuilderList() {
        return getFqListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder> 
          getFqListFieldBuilder() {
        if (fqListBuilder_ == null) {
          fqListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.FuturesQuoteSimpleDataBaseOrBuilder>(
                  fqList_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          fqList_ = null;
        }
        return fqListBuilder_;
      }

      private com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase fullFq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBaseOrBuilder> fullFqBuilder_;
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public boolean hasFullFq() {
        return fullFqBuilder_ != null || fullFq_ != null;
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase getFullFq() {
        if (fullFqBuilder_ == null) {
          return fullFq_ == null ? com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.getDefaultInstance() : fullFq_;
        } else {
          return fullFqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public Builder setFullFq(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase value) {
        if (fullFqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fullFq_ = value;
          onChanged();
        } else {
          fullFqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public Builder setFullFq(
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.Builder builderForValue) {
        if (fullFqBuilder_ == null) {
          fullFq_ = builderForValue.build();
          onChanged();
        } else {
          fullFqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public Builder mergeFullFq(com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase value) {
        if (fullFqBuilder_ == null) {
          if (fullFq_ != null) {
            fullFq_ =
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.newBuilder(fullFq_).mergeFrom(value).buildPartial();
          } else {
            fullFq_ = value;
          }
          onChanged();
        } else {
          fullFqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public Builder clearFullFq() {
        if (fullFqBuilder_ == null) {
          fullFq_ = null;
          onChanged();
        } else {
          fullFq_ = null;
          fullFqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.Builder getFullFqBuilder() {
        
        onChanged();
        return getFullFqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      public com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBaseOrBuilder getFullFqOrBuilder() {
        if (fullFqBuilder_ != null) {
          return fullFqBuilder_.getMessageOrBuilder();
        } else {
          return fullFq_ == null ?
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.getDefaultInstance() : fullFq_;
        }
      }
      /**
       * <code>optional .FuturesQuoteFullDataBase fullFq = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBaseOrBuilder> 
          getFullFqFieldBuilder() {
        if (fullFqBuilder_ == null) {
          fullFqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBase.Builder, com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.FuturesQuoteFullDataBaseOrBuilder>(
                  getFullFq(),
                  getParentForChildren(),
                  isClean());
          fullFq_ = null;
        }
        return fullFqBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MessageBase)
    }

    // @@protoc_insertion_point(class_scope:MessageBase)
    private static final com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase();
    }

    public static com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageBase>
        PARSER = new com.google.protobuf.AbstractParser<MessageBase>() {
      public MessageBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageBase> getParserForType() {
      return PARSER;
    }

    public com.waben.stock.futuresgateway.yisheng.common.protobuf.Message.MessageBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\032\rCommand.proto\032\026FuturesQ" +
      "uoteData.proto\032\034FuturesQuoteSimpleData.p" +
      "roto\032\032FuturesQuoteFullData.proto\"\346\001\n\013Mes" +
      "sageBase\022\020\n\010clientId\030\001 \001(\t\022\031\n\003cmd\030\002 \001(\0162" +
      "\014.CommandType\022\014\n\004type\030\003 \001(\003\022\023\n\013requestTy" +
      "pe\030\004 \001(\003\022\014\n\004data\030\005 \001(\t\022!\n\002fq\030\006 \001(\0132\025.Fut" +
      "uresQuoteDataBase\022+\n\006fqList\030\007 \003(\0132\033.Futu" +
      "resQuoteSimpleDataBase\022)\n\006fullFq\030\010 \001(\0132\031" +
      ".FuturesQuoteFullDataBaseBA\n6com.waben.s" +
      "tock.futuresgateway.yisheng.common.proto",
      "bufB\007Messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.getDescriptor(),
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.getDescriptor(),
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.getDescriptor(),
          com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.getDescriptor(),
        }, assigner);
    internal_static_MessageBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageBase_descriptor,
        new java.lang.String[] { "ClientId", "Cmd", "Type", "RequestType", "Data", "Fq", "FqList", "FullFq", });
    com.waben.stock.futuresgateway.yisheng.common.protobuf.Command.getDescriptor();
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteData.getDescriptor();
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteSimpleData.getDescriptor();
    com.waben.stock.futuresgateway.yisheng.common.protobuf.FuturesQuoteFullData.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
